[project]
name = "python-sketches"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests",
    "jsonpath_ng",
    "lxml",
    "pytest",
    "black"
]
